openapi: 3.0.0
info:
  title: API - Gestión de Usuarios (Ejemplo Básico)
  version: 1.0.0
  description: Una API simple para demostrar la funcionalidad CRUD básica.

# ----------------- SERVERS -----------------
# Define dónde se encuentra tu API (Debe coincidir con tu proxy de Docker)
servers:
  - url: http://backend/api # <--- URL de acceso DIRECTO interno al contenedor Apache
    description: Servidor de Desarrollo (Conexión Interna)
  - url: http://localhost:8090/idiomas/api # <--- URL de acceso EXTERNO a través de Nginx
    description: Servidor de Desarrollo (Nginx Proxy)
# ----------------- PATHS (RUTAS) -----------------
/v1/level/{id}:
get:
summary: Obtener un nivel por su ID
tags:
- Niveles
description: Recupera los detalles de un nivel de idioma específico utilizando su ID único.
parameters:
- name: id
in: path
required: true
schema:
type: integer
description: El ID único del nivel que se desea recuperar.
example: 3
responses:
'200':
description: Detalles del nivel recuperados exitosamente
content:
application/json:
schema:
$ref: '#/components/schemas/Nivel'
example:
id: 3
level_name: B1 Intermedio
description: Capaz de comprender los puntos principales de textos claros en lenguaje estándar.
id_level_coordinator: 12
'404':
description: Nivel no encontrado
'500':
description: Error interno del servidor