# Esto creará un alias /documentacion que apunta a la ruta física

Alias /documentacion "/var/www/html/documentacion"

<Directory "/var/www/html/documentacion">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

